### ISSUE TITLE
"The" TO-DO list

### ISSUE THREAD

**Issue by AryToNeX** [AryToNeX/Glasscord#21]
### Release 0.1
- [x] Relative CSS loader path support
- [x] Merge electron into master
- [x] Early access release on Patreon + Git tag
- [x] Bugfixing
- [x] ~~Release~~ Canceled since there were major bugs
### Release 0.2
- [x] Glasstron core library implementation (on a separate repo)
- [x] Introduce Glasstron as an npm module
- [x] Modify Glasscord so it works with Glasstron
- [x] Fix every regression; keep feature parity with release 0.1
- [x] Early access release on Patreon + Git tag
- [x] Bugfixing
- [x] Release (0.2.1 if some bugs were fixed)
### Release 1.0
- [x] Auto featured modules opt-out
- [x] Auto update should be disabled if the user can't modify the asar file because of FS permissions
- [x] Stable API for modules (onLoad, onShutdown)
- [x] PROPER MAC OS SUPPORT EVERYWHERE
- [x] Early access release on Patreon + Git tag
- [x] Bugfixing
- [x] Release (1.0.1 if some bugs were fixed)
#### Proposed
- [x] Support external module loading + "module repo"
- [x] Discord module as external
- [x] Glasscord should download "recommended" external modules directly

**Comment by abhijit-23blaze** [comment]
hi i am new to this

**Comment by PoorPocketsMcNewHold** [comment]
Hi new,

This is a TO-DO list, this is meant for other users to see the progress of the project to other users, and isn’t really meant to be commented on.

**Comment by sourTaste000** [comment]
Why doesn't use the project panel?
